### ISSUE TITLE
How do you generate the tiles ?

### ISSUE THREAD

**Issue by BigPino67** [Chenzo/sea-of-thieves-map#3]
How do you generate the tiles from the complete map image?

**Comment by Chenzo** [comment]
The full map tile set is here: https://github.com/Chenzo/sea-of-thieves-map-map

in its own repo cause it is large and doesn't change that often.

**Comment by BigPino67** [comment]
I mean,  how can I generate all the tiles if i want to create a new map design?

**Comment by Chenzo** [comment]
You need to replace this image with the one you want:

https://github.com/Chenzo/sea-of-thieves-map-map/blob/master/sot_map_v1_2X.jpg

You'll need to install and get this working:

https://github.com/commenthol/gdal2tiles-leaflet

and then the command is something liek this: `gdal2tiles2.py -l -p raster -w none -z 2-6 ./sot_map_v1.jpg tiles`
