### ISSUE TITLE
Url rewriting

### ISSUE THREAD

**Issue by BigPino67** [Chenzo/sea-of-thieves-map#5]
What do I have to do if i want the first parameter for language?

Ex : http://localhost/{LANG}/#4/-28.75/76.25

**Comment by Chenzo** [comment]
That's a little out of scope for this repo. But you can modify `updateQueryStringParam` in here: https://github.com/Chenzo/sea-of-thieves-map/blob/master/src/js/modules/tools.js
to read and detect your query vars.
